#! /bin/bash

_PWD=$(pwd)

echo "Shuffling!";

shuffle () {
#  Shuffle names list, into candidate bin
:>$_PWD/output
cat $_PWD/names | shuf > $_PWD/shuffle
}


loopOutput () {
#  Loop through the names/shuffle bin and 
#  compare if names are in the person's block list
while read -r a && read -r b <&3;
do
	cd $_PWD/blocklist
	
	if $(grep -q "$b" "$a")
	then
		_task="shuffle"
		break
        else

		_task="continue"
		echo -e "$a -> $b" >> $_PWD/output
	fi
done < $_PWD/shuffle 3<$_PWD/names

#  here's the end catch
#  if we've broken the loop, kick off
#  another shuffle
#  otherwise, output successful hash list
case "$_task" in
        shuffle)
	  shuffle
	  loopOutput
          ;;
        continue)
          cat $_PWD/output
          ;;
         
        *)
          echo "Unknown status";
	  exit 0
	  ;;
esac
}

#  initial kickoff
shuffle
loopOutput
